service:
  name: "api-gateway"
  port: "8083"
  allow_origins: ["https://dev-fab.thriwe.com", "https://stag-fab.thriwe.com", "https://prod-fab.thriwe.com", "https://fab.thriwe.com", "https://fab-admin.thriwe.com", "https://sme-stage.bankfab.com", "https://dev-admin.thriwe.com", "https://stag-admin.thriwe.com", "https://admin.thriwe.com", "https://smerewards.bankfab.com"]

FAB_BENEFITS_V1:
    base_url: "https://dev-fab-api-gateway.thriwe.com/parse/"
    application_id: "DEV_APPLICATION_ID"
    master_key: "DEV_MASTER_KEY"
    client_key: "DEV_CLIENT_KEY"
 
postgresql_parse_server:
  base_url: "https://dev.ext-api.thriwe.com/parse/"
  application_id: "APPLICATION_ID"
  master_key: "MASTER_KEY"
  Transactions-Server: 1

sqs:
  name: "dev-test-queue-1"
  region: "me-central-1"
    


